### PR TITLE
New: AWS AppSync App with React and Apollo

### PR DESCRIPTION
**Pull request by gyandeeps**
Twitter convo : https://twitter.com/gyandeeps/status/1005611965480349696
Which led to me writing this. 

I am not a good writer but I am trying to write more n more stuff

### CODE REVIEW

**Comment by gyandeeps** [comment]
Any feedback is highly appreciated @brettstack @dabit3 @undefobj

**Comment by gyandeeps** [comment]
I am going to merge this for now but feel free to give ur feedback folks. thanks

**Comment by dabit3** [comment]
Hey @gyandeeps I just went through all of this & it looks great. Did you find that using Apollo Link State works well with AWS AppSync?

**Comment by gyandeeps** [comment]
@dabit3 it did work well. There was no article out their which gave me a complete picture for an application.
Thanks a lot for a quick review.

**Comment by gyandeeps** [comment]
Here is the link live: https://gyandeeps.com/aws-appsync-graphql/

**Comment by dabit3** [comment]
@gyandeeps  Blog post looks awesome live! Quick question: where does `withClientState` come from? I'm guessing Apollo Link State? May want to add the referenced import, but I'm kind of new to Apollo Link State so I may be missing something.

**Comment by gyandeeps** [comment]
thanks @dabit3 . You are correct. I have updated the blog post.

**Pull request merged**
